# this file exists to copy/paste test data as needed

# merchant status:["disabled", "enabled"] disabled by default
merchant1 = create(:merchant, status: 1)
merchant2 = create(:merchant, status: 1)
merchant3 = create(:merchant, status: 1)
merchant4 = create(:merchant, status: 1)
merchant5 = create(:merchant, status: 1)
merchant6 = create(:merchant, status: 1)

# item status:["Disabled", "Enabled"] disabled by default
item1 = create(:item, unit_price: 100, status: 1, merchant: merchant1)
item2 = create(:item, unit_price: 100, status: 1, merchant: merchant2)
item3 = create(:item, unit_price: 100, status: 1, merchant: merchant3)
item4 = create(:item, unit_price: 100, status: 1, merchant: merchant4)
item5 = create(:item, unit_price: 100, status: 1, merchant: merchant5)
item6 = create(:item, unit_price: 100, status: 1, merchant: merchant6)
item7 = create(:item, unit_price: 100, status: 1, merchant: merchant1)
item8 = create(:item, unit_price: 100, status: 1, merchant: merchant2)
item9 = create(:item, unit_price: 100, status: 1, merchant: merchant3)
item10 = create(:item, unit_price: 100, status: 1, merchant: merchant4)
item11 = create(:item, unit_price: 100, status: 1, merchant: merchant5)
item12 = create(:item, unit_price: 100, status: 1, merchant: merchant6)

bulk_discount1 = BulkDiscount.create(percentage: 0.10, quantity_threshold: 10, merchant: merchant1)
bulk_discount2 = BulkDiscount.create(percentage: 0.11, quantity_threshold: 11, merchant: merchant2)
bulk_discount3 = BulkDiscount.create(percentage: 0.12, quantity_threshold: 12, merchant: merchant3)
bulk_discount4 = BulkDiscount.create(percentage: 0.13, quantity_threshold: 13, merchant: merchant4)
bulk_discount5 = BulkDiscount.create(percentage: 0.14, quantity_threshold: 14, merchant: merchant5)
bulk_discount6 = BulkDiscount.create(percentage: 0.15, quantity_threshold: 15, merchant: merchant6)
bulk_discount7 = BulkDiscount.create(percentage: 0.25, quantity_threshold: 20, merchant: merchant1)
bulk_discount8 = BulkDiscount.create(percentage: 0.26, quantity_threshold: 21, merchant: merchant2)
bulk_discount9 = BulkDiscount.create(percentage: 0.27, quantity_threshold: 22, merchant: merchant3)
bulk_discount10 = BulkDiscount.create(percentage: 0.28, quantity_threshold: 23, merchant: merchant4)
bulk_discount11 = BulkDiscount.create(percentage: 0.29, quantity_threshold: 24, merchant: merchant5)
bulk_discount12 = BulkDiscount.create(percentage: 0.30, quantity_threshold: 25, merchant: merchant6)

customer1 = create(:customer)
customer2 = create(:customer)
customer3 = create(:customer)
customer4 = create(:customer)
customer5 = create(:customer)
customer6 = create(:customer)

# invoice status:["in progress", "completed", "cancelled"] no default
invoice1 = create(:invoice, status: 0, customer: customer1)
invoice2 = create(:invoice, status: 0, customer: customer2)
invoice3 = create(:invoice, status: 0, customer: customer3)
invoice4 = create(:invoice, status: 0, customer: customer4)
invoice5 = create(:invoice, status: 0, customer: customer5)
invoice6 = create(:invoice, status: 0, customer: customer6)
invoice7 = create(:invoice, status: 0, customer: customer1)
invoice8 = create(:invoice, status: 0, customer: customer2)
invoice9 = create(:invoice, status: 0, customer: customer3)
invoice10 = create(:invoice, status: 0, customer: customer4)
invoice11 = create(:invoice, status: 0, customer: customer5)
invoice12 = create(:invoice, status: 0, customer: customer6)

#  transaction result:["success", "failed"] no default
transaction1 = create(:transaction, invoice: invoice1, result: 0)
transaction2 = create(:transaction, invoice: invoice2, result: 0)
transaction3 = create(:transaction, invoice: invoice3, result: 0)
transaction4 = create(:transaction, invoice: invoice4, result: 0)
transaction5 = create(:transaction, invoice: invoice5, result: 0)
transaction6 = create(:transaction, invoice: invoice6, result: 0)
transaction7 = create(:transaction, invoice: invoice7, result: 0)
transaction8 = create(:transaction, invoice: invoice8, result: 0)
transaction9 = create(:transaction, invoice: invoice9, result: 0)
transaction10 = create(:transaction, invoice: invoice10, result: 0)
transaction11 = create(:transaction, invoice: invoice11, result: 0)
transaction12 = create(:transaction, invoice: invoice12, result: 0)
transaction13 = create(:transaction, invoice: invoice1, result: 0)
transaction14 = create(:transaction, invoice: invoice2, result: 0)
transaction15 = create(:transaction, invoice: invoice3, result: 0)
transaction16 = create(:transaction, invoice: invoice4, result: 0)
transaction17 = create(:transaction, invoice: invoice5, result: 0)
transaction18 = create(:transaction, invoice: invoice6, result: 0)
transaction19 = create(:transaction, invoice: invoice7, result: 0)
transaction20 = create(:transaction, invoice: invoice8, result: 0)
transaction21 = create(:transaction, invoice: invoice9, result: 0)
transaction22 = create(:transaction, invoice: invoice10, result: 0)
transaction23 = create(:transaction, invoice: invoice11, result: 0)
transaction24 = create(:transaction, invoice: invoice12, result: 0)

# invoice_item status:["pending", "packaged", "shipped"] no default
invoice_item1 = create(:invoice_item, unit_price: 100, quantity: 1, status: 0, item: item1, invoice: invoice1)
invoice_item2 = create(:invoice_item, unit_price: 100, quantity: 1, status: 0, item: item2, invoice: invoice2)
invoice_item3 = create(:invoice_item, unit_price: 100, quantity: 1, status: 0, item: item3, invoice: invoice3)
invoice_item4 = create(:invoice_item, unit_price: 100, quantity: 1, status: 0, item: item4, invoice: invoice4)
invoice_item5 = create(:invoice_item, unit_price: 100, quantity: 1, status: 0, item: item5, invoice: invoice5)
invoice_item6 = create(:invoice_item, unit_price: 100, quantity: 1, status: 0, item: item6, invoice: invoice6)
invoice_item7 = create(:invoice_item, unit_price: 100, quantity: 1, status: 0, item: item1, invoice: invoice7)
invoice_item8 = create(:invoice_item, unit_price: 100, quantity: 1, status: 0, item: item2, invoice: invoice8)
invoice_item9 = create(:invoice_item, unit_price: 100, quantity: 1, status: 0, item: item3, invoice: invoice9)
invoice_item10 = create(:invoice_item, unit_price: 100, quantity: 1, status: 0, item: item4, invoice: invoice10)
invoice_item11 = create(:invoice_item, unit_price: 100, quantity: 1, status: 0, item: item5, invoice: invoice11)
invoice_item12 = create(:invoice_item, unit_price: 100, quantity: 1, status: 0, item: item6, invoice: invoice12)
invoice_item13 = create(:invoice_item, unit_price: 100, quantity: 1, status: 0, item: item2, invoice: invoice1)
invoice_item14 = create(:invoice_item, unit_price: 100, quantity: 1, status: 0, item: item3, invoice: invoice2)
invoice_item15 = create(:invoice_item, unit_price: 100, quantity: 1, status: 0, item: item4, invoice: invoice3)
invoice_item16 = create(:invoice_item, unit_price: 100, quantity: 1, status: 0, item: item5, invoice: invoice4)
invoice_item17 = create(:invoice_item, unit_price: 100, quantity: 1, status: 0, item: item6, invoice: invoice5)
invoice_item18 = create(:invoice_item, unit_price: 100, quantity: 1, status: 0, item: item1, invoice: invoice6)
invoice_item19 = create(:invoice_item, unit_price: 100, quantity: 1, status: 0, item: item2, invoice: invoice7)
invoice_item20 = create(:invoice_item, unit_price: 100, quantity: 1, status: 0, item: item3, invoice: invoice8)
invoice_item21 = create(:invoice_item, unit_price: 100, quantity: 1, status: 0, item: item4, invoice: invoice9)
invoice_item22 = create(:invoice_item, unit_price: 100, quantity: 1, status: 0, item: item5, invoice: invoice10)
invoice_item23 = create(:invoice_item, unit_price: 100, quantity: 1, status: 0, item: item6, invoice: invoice11)
invoice_item24 = create(:invoice_item, unit_price: 100, quantity: 1, status: 0, item: item1, invoice: invoice12)
